[package]
name = "obscure-hvp"
version = "0.2.0"
authors = ["Saeid Ghafari <saeid025@yahoo.com>"]
edition = "2024"
description = "A simple tool to extract and creatge obscure 1 hvp archives"
license = "MIT"
readme = "README.md"

[workspace]
members = ["structures"]

[workspace.dependencies]
binrw = "0.14"

[dependencies]
binrw.workspace = true
structures = { path = "structures" }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
walkdir = "2.4"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = "symbols"
